version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - rag-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      - PORT=8000
      - CORS_ORIGINS=http://localhost:5173,http://client:5173,http://localhost:3000
    volumes:
      - ./server/data:/app/data
      - chroma-data:/app/chroma_db
    ports:
      - "8000:8000"
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  chroma-data:
    driver: local

